### PR TITLE
[DI2-206] Add related articles to publication detail page

### PR DESCRIPTION
**Pull request by jonkoops**
This reverts commit 8103a1fbf2826b06fee639a1f2ca55cd1da2495a.

### CODE REVIEW

**Comment by jonkoops** [comment]
This PR should not be merged yet as some detail pages will break due to some missing fields in some of the content in the CMS.

**Comment by janjaap** [comment]
@jonkoops Can this PR be closed?

**Comment by jonkoops** [comment]
> @jonkoops Can this PR be closed?

This is a feature that was reverted that we still want to release at some point.

**Comment by janjaap** [comment]
@jonkoops There is no such story on the board. I'd suggest closing this PR; we can always get the code from this PR if we happen to need it in the future.

**Comment by janjaap** [comment]
Also no harm in closing the PR and removing the branch if the code can be gotten from the closed PR in the future.

**Pull request closed without merging**
